import type { NextPage } from 'next'
import Head from 'next/head';
import { CgCoffee } from "react-icons/cg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
         <title>Tupisz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <h3>See you soon... <CgCoffee/></h3>
    </main></>
  )
}

export default Home
